### ISSUE TITLE
Release Date sometimes becomes full ISO-8601 string

### ISSUE THREAD

**Issue by russellbanks** [jedieaston/Add-ARPEntries#3]
I can reproduce this with `TigerVNCproject.TigerVNC` version 1.12.0 where the release date is set as:
```yaml
ReleaseDate: 2021-11-10
```
But after running Add-ARPEntries.ps1 on that manifest, it becomes:
```yaml
ReleaseDate: 2021-11-10T00:00:00.0000000
```

**Comment by jedieaston** [comment]
That commit should've resolved it, let me know if it didn't (it worked for your test case).
